name: publish
on:
  push:
    branches:
      - main
      - dev
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: install dependencies
        run: pip install -e ".[dev]"
      - name: run publish script
        run: python ./scripts/publish.py
      - name: set variables
        id: data
        run: |
          echo "version=$(cat .github-version)" >> "${GITHUB_OUTPUT}"
          echo "tag=$(cat .github-tag)" >> "${GITHUB_OUTPUT}"
      - name: create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.data.outputs.tag}}',
              sha: context.sha
            })
